name: quality-control
on:
  pull_request:
    branches:
      - '**'

env:
  GO_VERSION: '1.22.1'
  GO111MODULE: on

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: morphy2k/revive-action@v2

  sec:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: securego/gosec@latest
        with:
          args: ./...

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - run: make test
    needs: [lint, sec]
