name: quality-control
on:
  pull_request:
    branches:
      - '**'

env:
  GO_VERSION: '1.22.1'

jobs:
  quality-control:
    name: Quality Control
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Setup Decencies
        run: make setup
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
      - name: Tests
        run: make test
